### ISSUE TITLE
Doesn't run on Simulator on M1 Apple Silicon Mac

### ISSUE THREAD

**Issue by mdivkovic-speech** [Flawion/KOControls#2]
Environment:

-macOS Ventura 13.1
-iOS 16.3
-Xcode 14.2

Problem:

It successfully runs on iPhone device, but on iOS simulator it shows an error : `No such module 'KOControls`.

**Comment by Flawion** [comment]
Hi Matej! 
I guess that you are using cocoapods and open project by „*.xcodeproj”, you have to open it by „*.workspace” to have access to the Pods dependencies. 
By the way, I noticed that example wasn't building properly for the ARMs because swiftlint was too old and supported only x86_64. The library itself should work fine. I checked that on m2 / Xcode 14.2. But give me a know if you have a problem with some concrete scenario it can be interesting :)
